hostname: server-1
cpu: arm-cortex-a72
arch: aarch64
os: linux

devices:
  - name: binary_two
    repo: repo-bin2
    version: "^v0.1.0"
    asset: "binary_two-*.tar.gz"
    extract: binary_two
    path: artifacts/repo-bin2/binary_two
    type: binary

  - name: plugin_two
    repo: repo-lib2
    version: "^v1.0.0"
    asset: "plugin_two-*.tar.gz"
    extract: plugin_two
    path: artifacts/repo-lib2/plugin_two
    type: lib