name: rebuild-packages

on:
  workflow_call:
    inputs:
      target:
        required: false
        type: string
      ref:
        required: false
        type: string
    secrets:
      PACKAGER_TOKEN:
        required: true

jobs:
  rebuild:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo-packager
        uses: actions/checkout@v4
        with:
          repository: Composable-Build/repo-packager
          token: ${{ secrets.PACKAGER_TOKEN }}
          path: repo-packager

      - name: Verify checkout
        run: |
          pwd
          ls -la
          ls -la repo-packager

      - name: Echo
        run: echo "rebuild packages ${{ github.event.client_payload.repo }}"

      - name: Rebuild packages
        run: python3 scripts/rebuild_packages.py --repo "${{ github.event.client_payload.repo }}" --tag "${{ github.event.client_payload.tag }}"
        working-directory: repo-packager
  