name: rebuild-packages

on:
  workflow_call:
    inputs:
      repo:
        required: true
        type: string
      tag:
        required: true
        type: string
    secrets:
      PACKAGER_TOKEN:
        required: true

jobs:
  rebuild:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo-packager
        uses: actions/checkout@v4
        with:
          repository: Composable-Build/repo-packager
          token: ${{ secrets.PACKAGER_TOKEN }}
          path: repo-packager

      - name: Echo
        run: echo "rebuild packages ${{ inputs.repo }}  ${{ inputs.tag }}"

      - name: Rebuild packages
        run: python3 scripts/rebuild_packages.py --repo "${{ inputs.repo }}" --tag "${{ inputs.tag }}" --token "${{ secrets.PACKAGER_TOKEN }}"
        working-directory: repo-packager
  